package module;

import core.Module;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * @author Tim
 *
 */
public class Problem2 implements Module
{

	@Override
	public void run()
	{
		int previousNumber = 1;
		int currentNumber = 2;
		int temp;
		int sum = 0;
		
		while(currentNumber < 4000000)
		{
			if(currentNumber % 2 == 0)
			{
				sum += currentNumber;
			}
			temp = currentNumber;
			currentNumber = previousNumber + currentNumber;
			previousNumber = temp;
		}
		
		System.out.println("Answer: " + sum);
	}

}
